"""empty message

Revision ID: 8fb2b3b87eba
Revises: adc8c3f8de18
Create Date: 2021-11-22 23:22:21.752560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fb2b3b87eba'
down_revision = 'adc8c3f8de18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_count')
    op.drop_table('file_contents')
    op.add_column('plant', sa.Column('set_profile', sa.Boolean(), nullable=False))
    op.add_column('plant', sa.Column('audio_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant', 'audio_count')
    op.drop_column('plant', 'set_profile')
    op.create_table('file_contents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_count',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
