"""empty message

Revision ID: a35e3a6132e4
Revises: 8fb2b3b87eba
Create Date: 2021-11-22 23:25:02.565316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35e3a6132e4'
down_revision = '8fb2b3b87eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('set_profile', sa.Boolean(), nullable=True))
    op.add_column('plant', sa.Column('audio_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant', 'audio_count')
    op.drop_column('plant', 'set_profile')
    # ### end Alembic commands ###
